#!/bin/bash

# Update /etc/hosts file to change localhost and facebook.com resolutions
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Restart networking for changes to take effect
sudo systemctl restart networking
