#!/bin/bash

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Change the IP address for localhost and facebook.com
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

