#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Remove the existing entries for localhost and facebook.com
sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# Add the new entries for localhost and facebook.com
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
